### PR TITLE
add support for attachments

### PR DESCRIPTION
**Pull request by carlqt**

### CODE REVIEW

**Review by nitsujri — APPROVED** [review]

**Comment by beirigo** [comment]
👶 👶 👶 👶

**Comment by tkbky** [comment]
@carlqt Would you mind to add some tests? because this is an abstraction that will be used across projects, just want to make sure it's safe & always.

**Comment by nitsujri** [comment]
@carlqt you could just make it a full blown output comparison like the other current tests.

**Comment by carlqt** [comment]
@tkbky @nitsujri Sorry guys, I don't want to waste time to setup and writing test for this. We should use that time for tickets on bom-dia/main-site instead. I just spin up a quick and dirty code to support attachments.

**Comment by nitsujri** [comment]
oh wtf @JamesWatling took away my tests!? or are they just stuffed someplace in Main-site?

**Comment by beirigo** [comment]
@nitsujri there are no tests.

**Comment by nitsujri** [comment]
@marcosbeirigo yeah it got left behind in mainsite's `send_grid_mailer_specs.rb`

**Comment by nitsujri** [comment]
@carlqt go ahead and merge this. I'm going to have another branch to bring back the tests and pull them out of `main-site`

**Pull request merged**
